# Generated by Django 5.2.1 on 2025-05-28 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_employee_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='suppliers',
            field=models.ManyToManyField(blank=True, related_name='products', to='main.supplier'),
        ),
    ]
